### ISSUE TITLE
Fatal error: One or more hosts failed while executing task 'instance_liveness'

### ISSUE THREAD

**Issue by exciting678** [CSL-KU/firesim-nvdla#12]
When I run the commad "firesim infrasetup", error show as follows:

`FireSim Manager. Docs: http://docs.fires.im
Running: infrasetup

Building FPGA software driver for FireSimNoNIC-FireSimRocketChipQuadCoreConfig-FireSimDDR3FRFCFSLLC4MBConfig90MHz
[192.168.2.71] Executing task 'instance_liveness'
[192.168.2.71] Checking if host instance is up...

Fatal error: One or more hosts failed while executing task 'instance_liveness'

Aborting.
Fatal error.
Traceback (most recent call last):
  File "/home/centos/firesim-nvdla/deploy/firesim", line 307, in <module>
    main(args)
  File "/home/centos/firesim-nvdla/deploy/firesim", line 255, in main
    globals()[args.task](simconf)
  File "/home/centos/firesim-nvdla/deploy/firesim", line 68, in infrasetup
    runtime_conf.infrasetup()
  File "/home/centos/firesim-nvdla/deploy/runtools/runtime_config.py", line 337, in infrasetup
    self.firesim_topology_with_passes.infrasetup_passes(use_mock_instances_for_testing)
  File "/home/centos/firesim-nvdla/deploy/runtools/firesim_topology_with_passes.py", line 355, in infrasetup_passes
    execute(instance_liveness, hosts=all_runfarm_ips)
  File "/usr/lib64/python2.7/site-packages/fabric/tasks.py", line 420, in execute
    error(err)
  File "/usr/lib64/python2.7/site-packages/fabric/utils.py", line 358, in error
    return func(message)
  File "/usr/lib64/python2.7/site-packages/fabric/utils.py", line 62, in abort
    raise e
SystemExit: 1
The full log of this run is:
/home/centos/firesim-nvdla/deploy/logs/2019-12-24--14-07-29-infrasetup-27KD2A9BRFKYK83K.log`

How to solve the problem? Thanks!

**Comment by exciting678** [comment]
I have solved the problem, thanks.

**Comment by farzad64** [comment]
Cool. May I ask what was causing the problem and how you fixed it?

**Comment by exciting678** [comment]
I failed add firesim.pem to ssh-agent at the beginning because of the permission problem, then I use "chmod 400 firesime.pem" to change the permision and it works. Thanks!

**Comment by farzad64** [comment]
Ok, let me know if you face any other issue.

**Comment by ku-researcher** [comment]
I encountered the same error.
According to the advice, I change the permission of the firesim.pem by executing following command 'chmod 400 firesim.pem'.
But, I can't eliminate the error.
Only by changing the permission,will the problem be solved?
Please give me the advice.

**Comment by ku-researcher** [comment]
I misunderstood.
I solved the problem.
Thank you.
