### ISSUE TITLE
source sourceme-f1-manager.sh error

### ISSUE THREAD

**Issue by lznnnnn1998** [CSL-KU/firesim-nvdla#24]
after i `source sourceme-f1-manager.sh`, it said 
-bash: env.sh: No such file or directory
success: firesim.pem available in ssh-agent
but when i do `./marshal -v build workloads/darknet-nvdla.json`, it said "Please source firesim/sourceme-manager-f1.sh first"

**Comment by lznnnnn1998** [comment]
build-setup.sh gave this log:
fatal: reference is not a tree: 380c233b43c2de53b0ee15a39e9364d438066b9f
Skipping submodule 'target-design/firechip/riscv-tools'
Skipping submodule 'target-design/firechip/rocket-chip/riscv-tools'
Unable to checkout '380c233b43c2de53b0ee15a39e9364d438066b9f' in submodule path 'sim/firrtl'

**Comment by farzad64** [comment]
I did a fresh clone and it works fine for me. Looks like it is a transient failure as David mentioned [here](https://github.com/firesim/firesim/issues/650#issuecomment-713012322). I would give it another try if I were you.

**Comment by lznnnnn1998** [comment]
after i did `./marshal install workloads/darknet-nvdla.json`, it said :
centos@ip-192-168-2-175.ec2.internal:~/firesim-nvdla$ cd sw/firesim-software/
centos@ip-192-168-2-175.ec2.internal:~/firesim-nvdla/sw/firesim-software$ ./marshal install workloads/darknet-nvdla.json                                              To check on progress, either call marshal with '-v' or see the live output at:
/home/centos/firesim-nvdla/sw/firesim-software/logs/darknet-nvdla-install-2020-10-21--03-10-16-1IL8N4KAD2BNDZPL.log
Log available at: /home/centos/firesim-nvdla/sw/firesim-software/logs/darknet-nvdla-install-2020-10-21--03-10-16-1IL8N4KAD2BNDZPL.log

**Comment by lznnnnn1998** [comment]
it cannot generate config file

**Comment by farzad64** [comment]
Could you share the log?

**Comment by lznnnnn1998** [comment]
i think it's my network disconnection. it now works

**Comment by lznnnnn1998** [comment]
but it cannot run `firesim infrasetup`
centos@ip-192-168-2-175.ec2.internal:~/firesim-nvdla/deploy$ firesim infrasetup    /usr/lib/python2.7/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
FireSim Manager. Docs: http://docs.fires.im
Running: infrasetup

Building FPGA software driver for FireSimNoNIC-FireSimRocketChipQuadCoreConfig_WithNVDLALarge-FireSimDDR3FRFCFSLLC4MBConfig75MHz
FPGA software driver build failed. Exiting. See log for details.
You can also re-run 'make DESIGN=FireSimNoNIC TARGET_CONFIG=FireSimRocketChipQuadCoreConfig_WithNVDLALarge PLATFORM_CONFIG=FireSimDDR3FRFCFSLLC4MBConfig75MHz f1' in the 'firesim/sim' directory to debug this error.
Fatal error.
Traceback (most recent call last):
  File "/home/centos/firesim-nvdla/deploy/firesim", line 307, in <module>
    main(args)
  File "/home/centos/firesim-nvdla/deploy/firesim", line 255, in main
    globals()[args.task](simconf)
  File "/home/centos/firesim-nvdla/deploy/firesim", line 68, in infrasetup
    runtime_conf.infrasetup()
  File "/home/centos/firesim-nvdla/deploy/runtools/runtime_config.py", line 337, in infrasetup
    self.firesim_topology_with_passes.infrasetup_passes(use_mock_instances_for_testing)
  File "/home/centos/firesim-nvdla/deploy/runtools/firesim_topology_with_passes.py", line 346, in infrasetup_passes
    self.pass_build_required_drivers()
  File "/home/centos/firesim-nvdla/deploy/runtools/firesim_topology_with_passes.py", line 329, in pass_build_required_drivers
    server.get_server_hardware_config().build_fpga_driver()
  File "/home/centos/firesim-nvdla/deploy/runtools/runtime_config.py", line 197, in build_fpga_driver
    exit(1)
  File "/usr/lib64/python2.7/site.py", line 364, in __call__
    raise SystemExit(code)
SystemExit: 1
The full log of this run is:
/home/centos/firesim-nvdla/deploy/logs/2020-10-21--03-24-36-infrasetup-03IWGVHJG7T9KIAH.log

**Comment by lznnnnn1998** [comment]
here is the log:
2020-10-21 03:24:36,706 [main        ] [INFO ]  FireSim Manager. Docs: http://docs.fires.im
Running: infrasetup

2020-10-21 03:24:36,707 [__init__    ] [DEBUG]  {'hwconf_dict': {'fireboom-singlecore-nic-ddr3-llc4mb': <runtools.runtime_config.RuntimeHWConfig instance at 0x7fb434a6ddd0>,
                 'fireboom-singlecore-no-nic-ddr3-llc4mb': <runtools.runtime_config.RuntimeHWConfig instance at 0x7fb434a6dd40>,
                 'firesim-quadcore-nic-ddr3-llc4mb': <runtools.runtime_config.RuntimeHWConfig instance at 0x7fb434a6dea8>,
                 'firesim-quadcore-no-nic-ddr3-llc4mb': <runtools.runtime_config.RuntimeHWConfig instance at 0x7fb434a6dd88>,
                 'firesim-quadcore-no-nic-nvdla-ddr3-llc4mb': <runtools.runtime_config.RuntimeHWConfig instance at 0x7fb434a6dcf8>,
                 'firesim-quadcore-no-nic-nvdla-small-ddr3-llc4mb': <runtools.runtime_config.RuntimeHWConfig instance at 0x7fb434a6def0>,
                 'firesim-singlecore-no-nic-lbp': <runtools.runtime_config.RuntimeHWConfig instance at 0x7fb434a6de18>,
                 'firesim-supernode-singlecore-nic-lbp': <runtools.runtime_config.RuntimeHWConfig instance at 0x7fb434a6de60>}}
2020-10-21 03:24:36,708 [__init__    ] [DEBUG]  {'defaulthwconfig': 'firesim-quadcore-no-nic-nvdla-ddr3-llc4mb',
 'f1_16xlarges_requested': 0,
 'f1_2xlarges_requested': 1,
 'f1_4xlarges_requested': 0,
 'linklatency': 6405,
 'm4_16xlarges_requested': 0,
 'netbandwidth': 200,
 'no_net_num_nodes': 1,
 'profileinterval': -1,
 'run_instance_market': 'ondemand',
 'runfarmtag': 'mainrunfarm',
 'spot_interruption_behavior': 'terminate',
 'spot_max_price': 'ondemand',
 'switchinglatency': 10,
 'terminateoncompletion': False,
 'topology': 'no_net_config',
 'trace_enable': False,
 'trace_end': -1,
 'trace_start': 0,
 'workload_name': 'darknet-nvdla.json'}
2020-10-21 03:24:36,714 [get_deploytr] [DEBUG]  Setting deploytriplet by querying the AGFI's description.
2020-10-21 03:24:36,714 [get_afi_for_] [DEBUG]  agfi-0ceed51cae44c4e59
2020-10-21 03:24:36,714 [get_afi_for_] [DEBUG]  None

**Comment by terryjx** [comment]
> i think it's my network disconnection. it now works

Could you help shed some light on how this issue could be resolved?

BTW, have you managed to generate env.sh using build-setup.sh  script?
